### ISSUE TITLE
An internal error issue

### ISSUE THREAD

**Issue by kishor786** [futurumclix/futurumclix#1]
I have installed the script but admin panel url doesnot work and all pages header and footer are works fine but middle is showing "An internal error" do not show any content.

**Comment by futurumclix** [comment]
Did you install it from release package or from repository? Server is Nginx or Apache?

**Comment by kishor786** [comment]
Yes I installed release package from repository and i am using Apache server.

## Installation time when i debug mode = 1 then show error

Warning (512): Method SessionHelper::consume does not exist [CORE/Cake/View/Helper.php, line 192]
Warning (512): Method SessionHelper::consume does not exist [CORE/Cake/View/Helper.php, line 192]
Warning (512): Method SessionHelper::consume does not exist [CORE/Cake/View/Helper.php, line 192]
note : When debug mode 0 then do not show any error.

# Error Log

2018-01-19 13:31:29 Error: [MissingActionException] Action InstallerController::install() could not be found.
Exception Attributes: array (
  'controller' => 'InstallerController',
  'action' => 'install',
)
Request URL: /install
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(InstallerController), Object(CakeRequest))
#2 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-01-19 13:39:37 Error: Fatal Error (4): syntax error, unexpected '$params' (T_VARIABLE) in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 195]
2018-01-19 13:39:37 Error: [FatalErrorException] syntax error, unexpected '$params' (T_VARIABLE)
Request URL: /
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/home/mpabaphr/...', 195)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/home/mpabaphr/...', 195, Array)
#2 /home/mpabaphr/public_html/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/home/mpabaphr/...', 195, Array)
#3 /home/mpabaphr/public_html/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-01-19 13:39:50 Error: Fatal Error (4): syntax error, unexpected '$params' (T_VARIABLE) in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 195]
2018-01-19 13:39:50 Error: [FatalErrorException] syntax error, unexpected '$params' (T_VARIABLE)
Request URL: /
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/home/mpabaphr/...', 195)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/home/mpabaphr/...', 195, Array)
#2 /home/mpabaphr/public_html/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/home/mpabaphr/...', 195, Array)
#3 /home/mpabaphr/public_html/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-01-19 13:44:42 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:44:42 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:44:42 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:44:47 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
Request URL: /step4
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Model/Datasource/DboSource.php(460): PDOStatement->execute(Array)
#1 /home/mpabaphr/public_html/lib/Cake/Model/Datasource/DboSource.php(426): DboSource->_execute('INSERT INTO `ar...', Array)
#2 /home/mpabaphr/public_html/lib/Cake/Model/Datasource/DboSource.php(668): DboSource->execute('INSERT INTO `ar...', Array, Array)
#3 /home/mpabaphr/public_html/lib/Cake/Model/Datasource/DboSource.php(539): DboSource->fetchAll('INSERT INTO `ar...')
#4 /home/mpabaphr/public_html/app/Plugin/Installer/Controller/InstallerController.php(465): DboSource->query('INSERT INTO `ar...')
#5 /home/mpabaphr/public_html/app/Plugin/Installer/Controller/InstallerController.php(478): InstallerController->_importSQL('/home/mpabaphr/...')
#6 [internal function]: InstallerController->step4()
#7 /home/mpabaphr/public_html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(InstallerController), Array)
#8 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(InstallerController), Object(CakeRequest))
#10 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2018-01-19 13:44:56 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /users/login
Stack Trace:
#0 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-01-19 13:45:01 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /pages/display/home
Stack Trace:
#0 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-01-19 13:45:07 Error: [MissingActionException] Action InstallerController::admin() could not be found.
Exception Attributes: array (
  'controller' => 'InstallerController',
  'action' => 'admin',
)
Request URL: /admin
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(InstallerController), Object(CakeRequest))
#2 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-01-19 13:45:24 Error: [MissingActionException] Action InstallerController::admin() could not be found.
Exception Attributes: array (
  'controller' => 'InstallerController',
  'action' => 'admin',
)
Request URL: /admin
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(InstallerController), Object(CakeRequest))
#2 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-01-19 13:45:39 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /pages/display/home
Stack Trace:
#0 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-01-19 13:48:00 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:00 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:00 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:05 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:05 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:05 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:17 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:17 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:17 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:21 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:21 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:21 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:31 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:31 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:31 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:37 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:37 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:37 Warning: Warning (512): Method SessionHelper::consume does not exist in [/home/mpabaphr/public_html/lib/Cake/View/Helper.php, line 192]
Trace:
Helper::__call() - CORE/Cake/View/Helper.php, line 192
SessionHelper::consume() - APP/View/Helper/NoticeHelper.php, line 101
NoticeHelper::show() - APP/View/Helper/NoticeHelper.php, line 101
include - APP/Plugin/Installer/View/Layouts/installer.ctp, line 29
View::_evaluate() - CORE/Cake/View/View.php, line 961
View::_render() - CORE/Cake/View/View.php, line 923
View::renderLayout() - CORE/Cake/View/View.php, line 546
View::render() - CORE/Cake/View/View.php, line 481
Controller::render() - CORE/Cake/Controller/Controller.php, line 960
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 200
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-19 13:48:58 Error: [MissingPluginException] Plugin DebugKit could not be found.
Exception Attributes: array (
  'plugin' => 'DebugKit',
)
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Core/CakePlugin.php(72): CakePlugin::load('DebugKit', Array)
#1 /home/mpabaphr/public_html/app/Config/bootstrap.php(138): CakePlugin::load(Array)
#2 /home/mpabaphr/public_html/lib/Cake/Core/Configure.php(92): include('/home/mpabaphr/...')
#3 /home/mpabaphr/public_html/lib/Cake/bootstrap.php(175): Configure::bootstrap(true)
#4 /home/mpabaphr/public_html/app/webroot/index.php(90): include('/home/mpabaphr/...')
#5 {main}
2018-01-19 13:49:07 Error: [MissingPluginException] Plugin DebugKit could not be found.
Exception Attributes: array (
  'plugin' => 'DebugKit',
)
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Core/CakePlugin.php(72): CakePlugin::load('DebugKit', Array)
#1 /home/mpabaphr/public_html/app/Config/bootstrap.php(138): CakePlugin::load(Array)
#2 /home/mpabaphr/public_html/lib/Cake/Core/Configure.php(92): include('/home/mpabaphr/...')
#3 /home/mpabaphr/public_html/lib/Cake/bootstrap.php(175): Configure::bootstrap(true)
#4 /home/mpabaphr/public_html/app/webroot/index.php(90): include('/home/mpabaphr/...')
#5 {main}
2018-01-19 13:49:09 Error: [MissingPluginException] Plugin DebugKit could not be found.
Exception Attributes: array (
  'plugin' => 'DebugKit',
)
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Core/CakePlugin.php(72): CakePlugin::load('DebugKit', Array)
#1 /home/mpabaphr/public_html/app/Config/bootstrap.php(138): CakePlugin::load(Array)
#2 /home/mpabaphr/public_html/lib/Cake/Core/Configure.php(92): include('/home/mpabaphr/...')
#3 /home/mpabaphr/public_html/lib/Cake/bootstrap.php(175): Configure::bootstrap(true)
#4 /home/mpabaphr/public_html/app/webroot/index.php(90): include('/home/mpabaphr/...')
#5 {main}
2018-01-19 13:49:15 Error: [MissingPluginException] Plugin DebugKit could not be found.
Exception Attributes: array (
  'plugin' => 'DebugKit',
)
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Core/CakePlugin.php(72): CakePlugin::load('DebugKit', Array)
#1 /home/mpabaphr/public_html/app/Config/bootstrap.php(138): CakePlugin::load(Array)
#2 /home/mpabaphr/public_html/lib/Cake/Core/Configure.php(92): include('/home/mpabaphr/...')
#3 /home/mpabaphr/public_html/lib/Cake/bootstrap.php(175): Configure::bootstrap(true)
#4 /home/mpabaphr/public_html/app/webroot/index.php(90): include('/home/mpabaphr/...')
#5 {main}

**Comment by kishor786** [comment]
When debug mode 1
http://prntscr.com/i2o902

When debug mode 0
http://prntscr.com/i2o9ob

**Comment by kishor786** [comment]
I have installed DebugKit and when i change it 0 same issue
