### ISSUE TITLE
Ads reports

### ISSUE THREAD

**Issue by lucryptoin** [futurumclix/futurumclix#11]
In Fresh template doesn't open a modal for report. https://prnt.sc/i6yuff
Chrome shows error: Failed to load ../ads/report/5a6b4cc5-1044-4e65-a9e2-4250c6367471: Response for preflight is invalid (redirect)

**Comment by futurumclix** [comment]
Please provide me some details about connection type to your site. Are you using encrypted (https) connection? Do you have turned on "Force SSL Connection" or "Disable SSL Connection On Forum" options? Does it happen on every kind of ad? Is connection to advertised site encrypted?

**Comment by lucryptoin** [comment]
Under the following settings the problem disappeared. 
https://prnt.sc/i7yjpr
Thanks
