### ISSUE TITLE
License doesnt support on free modul

### ISSUE THREAD

**Issue by alexistdev** [futurumclix/futurumclix#14]
Hello i was a paid member of futurumclix, and at my shop the addon modul has available, but when i 've installed on my site, the license doesnt support for my new modul. Even i re-download my license at my shop. Can you follow my request for updating my license to the developer , since the support is closed.
my account : alexistdev@gmail.com
thanks
regards
alex

**Comment by futurumclix** [comment]
Before you can install any modules not listed in license file, you need to update the script to the version 20180116. For more information please read #4, as this is probably a duplicate.

**Comment by alexistdev** [comment]
thanks for answering, i've check my shop panel, there is latest update version:
20170516 , idont recieve any version like 20180116

**Comment by futurumclix** [comment]
It should be in updates section, the file is named "FuturumClix_20171211_20180116.tar.gz". If it's not here, please check "Updates until" column in "Your products" section, as maybe your license updates date has passed.

**Comment by alexistdev** [comment]
i've migrate to free version, thanks
