### ISSUE TITLE
installing issue & java malware detected issue

### ISSUE THREAD

**Issue by alexistdev** [futurumclix/futurumclix#15]
I've install cakephp using softaculous, and i cant find "app" directory on my cakephp's directory.
can you guide me how to make installation, and also i cant upload evercookie which is detected a malware from my hosting.

**Comment by futurumclix** [comment]
I'm sorry, but I'm not familiar with Softaculous, so I can't help you with that. If you just want the script to be installed, not for developing but for testing/production I suggest using one of [release packages](https://github.com/futurumclix/futurumclix/releases). It's bundled with CakePHP 2.
Yes, some antimalware software can alert about Evercookie. When this happens you have only two options: add the Evercookie to the anitmalware software's exceptions list, or remove it (in case of removing, please do not forget to disable it in FuturumClix settings). For instructions about antimalware software you have, please ask your hosting provider.

**Comment by alexistdev** [comment]
thanks, the release packages work for me.
