### ISSUE TITLE
banner statistical going to error.

### ISSUE THREAD

**Issue by alexistdev** [futurumclix/futurumclix#16]
Hello,

when i tried to add banner into statistical, there is error. My banner dissapeared, and it will come back if i disable the banner statistical into static banner.

and here is the error on app/tmp/logs
2018-01-31 01:11:08 Warning: Warning (2): imagettftext(): Could not find/open font in [/home/alyastor/public_html/app/Model/Banner.php, line 295]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
imagettftext - [internal], line ??
Banner::getStatisticalPath() - APP/Model/Banner.php, line 295
BannersController::admin_image() - APP/Controller/BannersController.php, line 153
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 108

2018-01-31 01:11:08 Error: [InternalErrorException] Failed to draw text
Request URL: /admin/banners/image/1
Stack Trace:
#0 /home/alyastor/public_html/app/Controller/BannersController.php(153): Banner->getStatisticalPath('admin', '1234.12345678', '1234.12345678', NULL)
#1 [internal function]: BannersController->admin_image('1')
#2 /home/alyastor/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(BannersController), Array)
#3 /home/alyastor/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /home/alyastor/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(BannersController), Object(CakeRequest))
#5 /home/alyastor/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))

**Comment by futurumclix** [comment]
Please install some fonts (True Type format, *.ttf) into /app/Media/Fonts directory.

**Comment by alexistdev** [comment]
I’ve install some font but thereis still error. Please check it, I’ve install font:


Sent from Mail for Windows 10
