### ISSUE TITLE
About Cashout Using IDR Currency

### ISSUE THREAD

**Issue by alexistdev** [futurumclix/futurumclix#17]
I've used this script for my region country, which is using IDR Currency. But when i change the currencies into IDR , cashout cant be done, since there is none payment gateway available. Can you add manual transfer gateway for this script? 

If there is need for fee to do this , please email me at alexistdev@gmail.com

regards
alex

**Comment by futurumclix** [comment]
I can add a gateway which will save deposits/cashouts as pending allowing admin to process them manually. I should find some time for this in this week. I will let you know when I got this ready. Meanwhile, if you want to support developing of FuturumClix by donation you can use BTC/ETH (I just added addresses in the end of readme file).

**Comment by alexistdev** [comment]
Hello,
I don’t have BTC/ETH since its illegal payment method at my country, I can donate using cash from my bank account to your paypall account, using my virtual creditcard number from my bank account.

Regards
alex

Sent from Mail for Windows 10

**Comment by futurumclix** [comment]
Oh, I see. I would prefer to accept donations only by BTC/ETH as then everyone can check balances of those addresses and see how many donations were given. I want FuturumClix to be as open as it's possible. But don't worry, I will add this gateway regardless donations.

**Comment by futurumclix** [comment]
I added Manual Payment Gateway, which will allow to do manual deposits/cashouts regardless of selected site currency. Please check and let me know if that's enough for you to solve this issue.

**Comment by alexistdev** [comment]
i've tried installed this manual payment but when it activated its going to error.

2018-02-06 23:19:20 Error: [InternalErrorException] Failed to create new column in UserProfile
Request URL: /admin/settings/payments
Stack Trace:
#0 [internal function]: SettingsController->admin_payments()
#1 /home/alyastore/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(SettingsController), Array)
#2 /home/alyastore/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /home/alyastore/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SettingsController), Object(CakeRequest))
#4 /home/alyastore/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by futurumclix** [comment]
I'm sorry, I forgot to mention - please also apply patch from commit 26e357909f94accb36e26ece9458370f6666e23d.

**Comment by alexistdev** [comment]
Hello thanks very much it works,

but there is a little issue, when i clicked "i've paid" there is instantly my account balance credited, which is without admin approval.
