### ISSUE TITLE
Tooltips on the cashout page

### ISSUE THREAD

**Issue by lucryptoin** [futurumclix/futurumclix#18]
For Fresh template.
In your demo page http://demo.futurumclix.com/users/cashout there are tooltips http://prntscr.com/i8jn9h
I have installed a version 1.7.2 and no tooltips.
For example I change the payment account and the button is disabled but no tooltips. https://prnt.sc/i8jw9z
In the Default template it works fine http://prntscr.com/i8jyou

**Comment by futurumclix** [comment]
For me it looks like is working, but there was chance that account was set to string containing only whitespaces. This may caused problems with tooltips. However setting it via user profile edit page should prevent that - did you use external tools (for example phpMyAdmin) to edit entries in database? What value did you set to cause problems with tooltip?

**Comment by lucryptoin** [comment]
I updated the file, but the problem with the hints remained. Tooltips for unchanged entries work well and show the name of the payment system. But for disabled buttons do not work. I forcibly changed payment accounts to check the operation of the tooltips. All changes I've done without external tools. Only through editing a profile in the Fresh template.

**Comment by futurumclix** [comment]
What browser do you use? It look like in Firefox tooltips works, but in Google Chrome not, because in Chrome [disabled elements do not trigger any events](https://github.com/uikit/uikit/issues/422). I will try to find workaround for this.

**Comment by lucryptoin** [comment]
Yes in Firefox tooltips works.

**Comment by futurumclix** [comment]
I added a workaround for this issue, please check if it solves the problem and let me know.

**Comment by lucryptoin** [comment]
Now it works even in Chrome. The buttons only look not as disabled but they are not active. Now everything is fine.

**Comment by futurumclix** [comment]
OK, thanks, so I will close this issue. If you want to edit the look of buttons feel free to edit related css and submit a pull request or a patch. I'm not as good in view related things as I would like to be. ;-)
