### ISSUE TITLE
Cron Jobs Adding and error issue

### ISSUE THREAD

**Issue by kishor786** [futurumclix/futurumclix#19]
Hello

I have added cron job commands code from admin panel cron settings into server cron tab and still i am facing that Admin Panel showing cron errors so what is the problem ?

Thanks

**Comment by futurumclix** [comment]
The notices will be gone after first run of corresponding cron-job, so you probably just need to wait (no longer than 24 hours - "daily" cron-job is running with this interval).

**Comment by kishor786** [comment]
It has 2 days gone but cron does not running. It added two days ago but no result.

**Comment by futurumclix** [comment]
OK, so let's check the configuration. First of all - do you use CPanel on your server? Maybe you could provide some screenshots of cronjobs configuration?

**Comment by kishor786** [comment]
Yes i am using CPanel.
http://prntscr.com/ich6tc

**Comment by futurumclix** [comment]
If you are using CPanel you need to use little workaround to make cronjobs running. First, go to the "Cron Settings" in Admin's Panel, check the "Allow running cron jobs via HTTP(S)" checkbox and set your server's IP as "HTTP(S) Allowed IPs". Then in CPanel change cronjobs commands to:
lynx --dump "http://<your-server-address>/crons/run/daily"
lynx --dump "http://<your-server-address>/crons/run/frequent"
lynx --dump "http://<your-server-address>/crons/run/botSystem"
Please replace <your-server-address> with address of your server and also change http:// to https:// if you are using secure connection.

If you found any other problems let me know about them - say when error occurred, post the message displayed to you, attach a log, but please open one issue per problem, as this way it's much more efficient for me to work. :-)

**Comment by kishor786** [comment]
1. Botcron has been run
2. Frequent cron fire should be every 10 minutes but my server load minimum 15 minutes and i have changed the value */15 and changed the code from AdminsController 15 minutes but cron not fire.

**Comment by lucryptoin** [comment]
I use the following settings and cron works correctly.
https://prnt.sc/icpieq
https://prnt.sc/icpijm

**Comment by futurumclix** [comment]
@lucryptoin Thanks for sharing your solution. 👍 
@kishor786 If only one cronjob is not running please recheck the configuration and also check if there is something related to this cronjob in app/tmp/logs/error.log.

**Comment by kishor786** [comment]
2018-02-10 12:45:28 Error: [SocketException] Invalid email: ""
Request URL: /crons/run/frequent
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(592): CakeEmail->_validateEmail('')
#1 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(642): CakeEmail->_setEmail('_from', '', '')
#2 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(387): CakeEmail->_setEmailSingle('_from', '', '', 'From requires o...')
#3 /home/mpabaphr/public_html/app/Model/PendingEmail.php(113): CakeEmail->from('', '')
#4 /home/mpabaphr/public_html/app/Console/Command/EmailShell.php(67): PendingEmail->send(Array, 'mohammadbd786@g...')
#5 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(459): EmailShell->send()
#6 /home/mpabaphr/public_html/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('send', Array)
#7 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(399): ShellDispatcher->dispatch()
#8 /home/mpabaphr/public_html/app/Console/Command/CronShell.php(93): Shell->dispatchShell('Email send')
#9 /home/mpabaphr/public_html/lib/Cake/Core/CakeObject.php(120): CronShell->frequent()
#10 /home/mpabaphr/public_html/app/Controller/CronsController.php(86): CakeObject->dispatchMethod('frequent')
#11 [internal function]: CronsController->run('frequent')
#12 /home/mpabaphr/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(CronsController), Array)
#13 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(CronsController), Object(CakeRequest))
#15 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2018-02-10 13:00:40 Error: [SocketException] Invalid email: ""
Request URL: /crons/run/frequent
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(592): CakeEmail->_validateEmail('')
#1 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(642): CakeEmail->_setEmail('_from', '', '')
#2 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(387): CakeEmail->_setEmailSingle('_from', '', '', 'From requires o...')
#3 /home/mpabaphr/public_html/app/Model/PendingEmail.php(113): CakeEmail->from('', '')
#4 /home/mpabaphr/public_html/app/Console/Command/EmailShell.php(67): PendingEmail->send(Array, 'mohammadbd786@g...')
#5 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(459): EmailShell->send()
#6 /home/mpabaphr/public_html/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('send', Array)
#7 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(399): ShellDispatcher->dispatch()
#8 /home/mpabaphr/public_html/app/Console/Command/CronShell.php(93): Shell->dispatchShell('Email send')
#9 /home/mpabaphr/public_html/lib/Cake/Core/CakeObject.php(120): CronShell->frequent()
#10 /home/mpabaphr/public_html/app/Controller/CronsController.php(86): CakeObject->dispatchMethod('frequent')
#11 [internal function]: CronsController->run('frequent')
#12 /home/mpabaphr/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(CronsController), Array)
#13 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(CronsController), Object(CakeRequest))
#15 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2018-02-10 13:15:23 Error: [SocketException] Invalid email: ""
Request URL: /crons/run/frequent
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(592): CakeEmail->_validateEmail('')
#1 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(642): CakeEmail->_setEmail('_from', '', '')
#2 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(387): CakeEmail->_setEmailSingle('_from', '', '', 'From requires o...')
#3 /home/mpabaphr/public_html/app/Model/PendingEmail.php(113): CakeEmail->from('', '')
#4 /home/mpabaphr/public_html/app/Console/Command/EmailShell.php(67): PendingEmail->send(Array, 'mohammadbd786@g...')
#5 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(459): EmailShell->send()
#6 /home/mpabaphr/public_html/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('send', Array)
#7 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(399): ShellDispatcher->dispatch()
#8 /home/mpabaphr/public_html/app/Console/Command/CronShell.php(93): Shell->dispatchShell('Email send')
#9 /home/mpabaphr/public_html/lib/Cake/Core/CakeObject.php(120): CronShell->frequent()
#10 /home/mpabaphr/public_html/app/Controller/CronsController.php(86): CakeObject->dispatchMethod('frequent')
#11 [internal function]: CronsController->run('frequent')
#12 /home/mpabaphr/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(CronsController), Array)
#13 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(CronsController), Object(CakeRequest))
#15 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2018-02-10 13:28:10 Error: [MissingControllerException] Controller class Robots.txtController could not be found.
Exception Attributes: array (
  'class' => 'Robots.txtController',
  'plugin' => NULL,
)
Request URL: /robots.txt
Stack Trace:
#0 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-02-10 13:28:17 Error: [MissingControllerException] Controller class Ads.txtController could not be found.
Exception Attributes: array (
  'class' => 'Ads.txtController',
  'plugin' => NULL,
)
Request URL: /ads.txt
Stack Trace:
#0 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-02-10 13:30:34 Error: [SocketException] Invalid email: ""
Request URL: /crons/run/frequent
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(592): CakeEmail->_validateEmail('')
#1 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(642): CakeEmail->_setEmail('_from', '', '')
#2 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(387): CakeEmail->_setEmailSingle('_from', '', '', 'From requires o...')
#3 /home/mpabaphr/public_html/app/Model/PendingEmail.php(113): CakeEmail->from('', '')
#4 /home/mpabaphr/public_html/app/Console/Command/EmailShell.php(67): PendingEmail->send(Array, 'mohammadbd786@g...')
#5 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(459): EmailShell->send()
#6 /home/mpabaphr/public_html/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('send', Array)
#7 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(399): ShellDispatcher->dispatch()
#8 /home/mpabaphr/public_html/app/Console/Command/CronShell.php(93): Shell->dispatchShell('Email send')
#9 /home/mpabaphr/public_html/lib/Cake/Core/CakeObject.php(120): CronShell->frequent()
#10 /home/mpabaphr/public_html/app/Controller/CronsController.php(86): CakeObject->dispatchMethod('frequent')
#11 [internal function]: CronsController->run('frequent')
#12 /home/mpabaphr/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(CronsController), Array)
#13 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(CronsController), Object(CakeRequest))
#15 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2018-02-10 13:35:24 Error: [MissingControllerException] Controller class Robots.txtController could not be found.
Exception Attributes: array (
  'class' => 'Robots.txtController',
  'plugin' => NULL,
)
Request URL: /robots.txt
Stack Trace:
#0 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-02-10 13:35:42 Error: [MissingControllerException] Controller class Ads.txtController could not be found.
Exception Attributes: array (
  'class' => 'Ads.txtController',
  'plugin' => NULL,
)
Request URL: /ads.txt
Stack Trace:
#0 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-02-10 13:45:28 Error: [SocketException] Invalid email: ""
Request URL: /crons/run/frequent
Stack Trace:
#0 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(592): CakeEmail->_validateEmail('')
#1 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(642): CakeEmail->_setEmail('_from', '', '')
#2 /home/mpabaphr/public_html/lib/Cake/Network/Email/CakeEmail.php(387): CakeEmail->_setEmailSingle('_from', '', '', 'From requires o...')
#3 /home/mpabaphr/public_html/app/Model/PendingEmail.php(113): CakeEmail->from('', '')
#4 /home/mpabaphr/public_html/app/Console/Command/EmailShell.php(67): PendingEmail->send(Array, 'mohammadbd786@g...')
#5 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(459): EmailShell->send()
#6 /home/mpabaphr/public_html/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('send', Array)
#7 /home/mpabaphr/public_html/lib/Cake/Console/Shell.php(399): ShellDispatcher->dispatch()
#8 /home/mpabaphr/public_html/app/Console/Command/CronShell.php(93): Shell->dispatchShell('Email send')
#9 /home/mpabaphr/public_html/lib/Cake/Core/CakeObject.php(120): CronShell->frequent()
#10 /home/mpabaphr/public_html/app/Controller/CronsController.php(86): CakeObject->dispatchMethod('frequent')
#11 [internal function]: CronsController->run('frequent')
#12 /home/mpabaphr/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(CronsController), Array)
#13 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /home/mpabaphr/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(CronsController), Object(CakeRequest))
#15 /home/mpabaphr/public_html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}

**Comment by futurumclix** [comment]
OK, now I know what happen. Before I fixed #7 you added to pending_emails entries with not set sending address. Please remove any entires from pending_emails table with some external tool (AFAIK there is phpMyAdmin bundled in CPanel). This should fix your issue.
