### ISSUE TITLE
An Internal error  occured

### ISSUE THREAD

**Issue by kishor786** [futurumclix/futurumclix#2]
I have installed debugkit and script loading right way but i could not login admin panel and user panel

**Comment by futurumclix** [comment]
It should be fixed now, please try with [version 1.7.1](https://github.com/futurumclix/futurumclix/releases/tag/v1.7.1). DebugKit should be no more needed to start the script, but if present, it will be automatically loaded. Additionally I fixed some issues with installation when debug level was set to 0.

**Comment by kishor786** [comment]
It has been installed perfectly and no errors are showing but Highcharts want installation and it is not showing. From admin panel i could not edit users because input and button like disabled

**Comment by kishor786** [comment]
Highchart has been installed

**Comment by jennyfer12300** [comment]
hello i installed the script but i have a mod_rewiter error but i do not know how to fix it i have a dedicated server
