### ISSUE TITLE
Installing on centos whmcpanel server. cake php not detecting modrewrite module

### ISSUE THREAD

**Issue by regedittap** [futurumclix/futurumclix#26]
Installing on centos whmcpanel server. cake php not detecting modrewrite module
![screenshot 2018-02-26 21 05 26](https://user-images.githubusercontent.com/8253590/36672810-b0a34170-1b3b-11e8-9a56-4b2f73bdc738.png)

Sorry but you need to have URL rewriting enabled on your server in order to install FuturumClix. Please check our Installation Manual for more details.

**Comment by shamuel22** [comment]
Same error

**Comment by shamuel22** [comment]
![image](https://user-images.githubusercontent.com/16228257/36950104-7cf7aa9c-1fc7-11e8-86fc-f58bc0233d6d.png)

**Comment by shamuel22** [comment]
Help @regedittap

**Comment by futurumclix** [comment]
@regedittap, @shamuel22 
Do you have your own servers with CentOS and CPanel or those are rented from some provider? Are you sure the rewrite module is installed and just not detected properly?

**Comment by shamuel22** [comment]
@futurumclix Im use VPS server whit CentOs 7 and WHM/cPanel. rewrite module is installed

**Comment by futurumclix** [comment]
I fixed test which causes this issue. Please check if it works now and let me know.

**Comment by shamuel22** [comment]
@futurumclix 

Another error... When I press the "continue" button, nothing happens. It just does not take me anywhere. 

Check mi site: http://infomoviee.com/

![image](https://user-images.githubusercontent.com/16228257/37796708-48253516-2dee-11e8-9540-88643340f1f4.png)

**Comment by futurumclix** [comment]
It looks like there is still some problems with url rewriting. Could you show me your nginx configuration file?

**Comment by shamuel22** [comment]
@futurumclix  its work now!!! :1st_place_medal:

**Comment by futurumclix** [comment]
I'm glad. Thank you for your cooperation and patience. :-) Don't hestitate to open another issue if you found another bugs.

**Comment by shamuel22** [comment]
@futurumclix see thist, is normal?

![image](https://user-images.githubusercontent.com/16228257/37802376-8fbf1dd0-2e00-11e8-9402-2077ac99ee27.png)

**Comment by futurumclix** [comment]
There is nothing in futurumclix code witch can cause that. For me it looks like something free hosting provider may add. Please ask your hosting provider.

**Comment by shamuel22** [comment]
It is not a free hosting, I use Hostgator 

![image](https://user-images.githubusercontent.com/16228257/37802633-ae8feb44-2e01-11e8-971c-cb5ef2890633.png)

**Comment by shamuel22** [comment]
Only appears when login

**Comment by shamuel22** [comment]
it's very strange :(

**Comment by shamuel22** [comment]
Maybe
![image](https://user-images.githubusercontent.com/16228257/37802729-025c30ac-2e02-11e8-9362-b5f4fabc8a47.png)

**Comment by futurumclix** [comment]
No, this is not related. You can disable evercookie from settings in admin's panel and check. If you have problems with evercookie please check if you have soft link /app/webroot/evercookie pointing to /app/Plugins/Evercookie/webroot.

**Comment by shamuel22** [comment]
Turn off everCookie and the problem was fixed

**Comment by shamuel22** [comment]
Defaut config no work ../Plugin/Evercookie/webroot

**Comment by shamuel22** [comment]
Yes, the problem is whit Evercookie
