### ISSUE TITLE
Paid Offer Ads Edited Offside on targeting location

### ISSUE THREAD

**Issue by alexistdev** [futurumclix/futurumclix#29]
when I tried to edit one of my active paid offer ad, there was an error. Targeting location option become offside, did not fit the place:

https://s14.postimg.org/4t1tu3of5/paidoffer_edit.png

**Comment by shamuel22** [comment]
@alexistdev pls help me to install this script

**Comment by lucryptoin** [comment]
[/app/View/Themed/Fresh/PaidOffers/edit.ctp](url)

<?=$this->element('userBreadcrumbs')?>
<div class="uk-container dashpage">
	<div class="uk-grid">
		<?=$this->element('userSidebar')?>
		<div class="uk-width-3-4@m">
			<?=$this->Notice->show()?>
			<h2 class="uk-margin-top"><?=__('Paid Offers Panel')?></h2>
			<?=
				$this->element('adsPanelBoxes', array(
				'add' => array('controller' => 'paid_offers', 'action' => 'add'),
				'buy' => array('controller' => 'paid_offers', 'action' => 'buy'),
				'assign' => array('controller' => 'paid_offers', 'action' => 'assign'),
				))
				?>
			<h2 class="uk-margin-top"><?=__('Edit advertisement')?></h2>
			<?=$this->UserForm->create('PaidOffer', array('class' => 'uk-form-horizontal'))?>
			<?=$this->UserForm->input('PaidOffer.id')?>
			<div class="uk-margin">
				<label class="uk-form-label">
					<?=__('Title')?>
					<div id="titleCounter" class="uk-badge"><?=isset($this->request->data['PaidOffer']['title']) ? strlen($this->request->data['PaidOffer']['title']) : 0?> / <?=$titleMax?></div>
				</label>
				<?=
					$this->UserForm->input('title', array(
					'palaceholder' => __('Enter your offertitle'),
					'class' => 'uk-input',
					'data-limit' => $titleMax,
					'data-counter' => 'titleCounter'
					))
					?>
			</div>
			<div class="uk-margin">
				<label class="uk-form-label">
					<?=__('Description')?>
					<div id="descCounter" class="uk-badge"><?=isset($this->request->data['PaidOffer']['description']) ? strlen($this->request->data['PaidOffer']['description']) : 0?> / <?=$descMax?></div>
				</label>
				<?=
					$this->UserForm->input('description', array(
					'type' => 'textarea',
					'class' => 'uk-textarea',
					'placeholder' => __('Please describe in details what applicant have to do to get this offer approved and what info has to be provided after submitting this offer.'),
					'style' => 'resize:none;',
					'data-limit' => $descMax,
					'data-counter' => 'descCounter',
					))
					?>
			</div>
			<div class="uk-margin">
				<label class="uk-form-label"><?=__('URL')?></label>
				<?=
					$this->UserForm->input('url', array(
					'class' => 'uk-input',
					'placeholder' => 'http://',
					))
					?>
			</div>
			<div class="uk-margin">
				<label class="uk-form-label"><?=__('Category')?></label>
				<?=$this->UserForm->input('category_id', array('class' => 'uk-select'))?>
			</div>
			<div class="uk-margin">
				<label class="uk-form-label"><?=__('Targeted Memberships')?></label>
				<?=
					$this->UserForm->input('TargettedMemberships', array(
					'type' => 'select',
					'class' => 'uk-textarea',
					'multiple' => 'multiple',
					'options' => $memberships,
					))
					?>
				<input class="nk-btn nk-btn-color-main" type="button" value="<?=__('Select All')?>" style="vertical-align: top;" onclick="selectAll('TargettedMembershipsTargettedMemberships')">
			</div>
			<?php if(Module::active('AccurateLocationDatabase')): ?>
			<?=$this->Locations->selector($countries)?>
			<?php else: ?>
			<div class="uk-margin">
				<label class="uk-form-label"><?=__('Targeted Locations')?></label>
				<?=
					$this->UserForm->input('TargettedLocations', array(
					'type' => 'select',
					'class' => 'uk-textarea',
					'multiple' => 'multiple',
					'options' => $countries,
					'selected' => $selectedCountries,
					))
					?>
				<input class="nk-btn nk-btn-color-main" type="button" value="<?=__('Select All')?>" style="vertical-align: top;" onclick="selectAll('PaidOfferTargettedLocations')">
			</div>
			<?php endif; ?>
			<div class="uk-margin uk-text-right">
				<button class="nk-btn nk-btn-color-main"><?=__('Edit Paid Offers')?></button>
			</div>
			<?=$this->UserForm->end()?>
		</div>
	</div>
</div>

One line with an error. Just change the button styles to yours.
https://prnt.sc/ipjb27

**Comment by futurumclix** [comment]
This is "Fresh" theme, isn't it? Was this happened on some mobile device or regular PC? In what web browser this happens? What's your screen resolution? What was the browser window size?

**Comment by alexistdev** [comment]
yes this on "fresh" template , i've checked it with regular PC. And at my case, i've solved this problem by copied just on "targeted location" section using code from file PTC ads/edit.ctp

i dont know where is the problem is, but by replacing the some code on paidoffer edit.ctp using ptc edit.ctp , it solved this problem. May be on next release you can fix this issue. May be there is miss 1 character , i dont know.

**Comment by futurumclix** [comment]
Fixed, thanks for hint. 👍
