### ISSUE TITLE
Please Help to install HighCharts

### ISSUE THREAD

**Issue by keysonv** [futurumclix/futurumclix#3]
Hi, I installed the plugin and it's great,
I would love to know how to install HighCharts,
Since I have no idea how to do it.

**Comment by futurumclix** [comment]
All you need to do is just copy highcharts.js file to app/webroot/js/charts directory. If directory is missing, create one. Also make sure file is readable by your HTTP server.

**Comment by keysonv** [comment]
Thank you so much.
