### ISSUE TITLE
Traffic Exchange Issue

### ISSUE THREAD

**Issue by kishor786** [futurumclix/futurumclix#5]
1. I have activated TrafficExchange module but i could not find the any create and edit option in admin panel.

2. RevenueShare "ADD NEW REVENUE SHARE PACK" into Items Included In This Pack there has no show any pack it is full blank.

3. When enable email verification system from admin panel. I tried to many times for sign up but when i submit the from then show "An Internal Error Has Occurred" and do not sent any email.

4. From admin panel user edit option. go to action and send- email function do not work show "An Internal Error Has Occurred"

**Comment by futurumclix** [comment]
1. The TrafficExchange module was never finished. It contains some code so it's visible in Modules section of admin panel, but it has no logic implemented so unfortunately it won't work.

2. There is a issue with creation of default values for configuration. I will fix it.

3. & 4. It looks like configuration issue. Please enable debug mode and keep it enabled for any tests, as it causes the error messages to be more descriptive or check error.log and post full message here.

**Comment by futurumclix** [comment]
I closed this issue, as I fixed problem with RevenueShares module. If you need any help with 3. or 4. feel free to open another issue.
