### ISSUE TITLE
Empty items list in add new RevenueShare form

### ISSUE THREAD

**Issue by kishor786** [futurumclix/futurumclix#6]
I have have been paste the code and update as you told. This issue may not fixed because item is not showing
http://prntscr.com/i4njx9

**Comment by futurumclix** [comment]
To have any elements in this list you also need to add some packages in site options. For example, go to the "Advertisements"->"Featured Ads Settings" then:
1. check "Enable Featured Ads" box
2. click "Save"
3. switch to the "Click Packages" tab
4. select "Type", set the "Amount" and "Price"
5. click "Save Changes"
After that you will see the item in the list.
