### ISSUE TITLE
Promotion Banner Upload And Input URL Issue

### ISSUE THREAD

**Issue by kishor786** [futurumclix/futurumclix#7]
1. When i choose file for banner upload then click add button it is redirect error page. Upload and URL add do not work and save the file.

2. Send email from admin panel it is not work. When send a email it is showing "an internal error occurred"

**Comment by futurumclix** [comment]
Please enable debug mode and post full error messages.

**Comment by kishor786** [comment]
## Banner Upload Error
Stack Trace
[internal function] → AppController->_badRequest(string)
CORE/Cake/Controller/Component/SecurityComponent.php line 831 → call_user_func_array(array, array)
CORE/Cake/Controller/Component/SecurityComponent.php line 351 → SecurityComponent->_callback(BannersController, string, array)
CORE/Cake/Controller/Component/SecurityComponent.php line 255 → SecurityComponent->blackHole(BannersController, string, AuthSecurityException)
[internal function] → SecurityComponent->startup(BannersController)
CORE/Cake/Utility/ObjectCollection.php line 128 → call_user_func_array(array, array)
[internal function] → ObjectCollection->trigger(CakeEvent)
CORE/Cake/Event/CakeEventManager.php line 243 → call_user_func(array, CakeEvent)
CORE/Cake/Controller/Controller.php line 678 → CakeEventManager->dispatch(CakeEvent)
CORE/Cake/Routing/Dispatcher.php line 189 → Controller->startupProcess()
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(BannersController, CakeRequest)
APP/webroot/index.php line 108 → Dispatcher->dispatch(CakeRequest, CakeResponse)

## Banner Url Error
Stack Trace
[internal function] → AppController->_badRequest(string)
CORE/Cake/Controller/Component/SecurityComponent.php line 831 → call_user_func_array(array, array)
CORE/Cake/Controller/Component/SecurityComponent.php line 351 → SecurityComponent->_callback(BannersController, string, array)
CORE/Cake/Controller/Component/SecurityComponent.php line 255 → SecurityComponent->blackHole(BannersController, string, AuthSecurityException)
[internal function] → SecurityComponent->startup(BannersController)
CORE/Cake/Utility/ObjectCollection.php line 128 → call_user_func_array(array, array)
[internal function] → ObjectCollection->trigger(CakeEvent)
CORE/Cake/Event/CakeEventManager.php line 243 → call_user_func(array, CakeEvent)
CORE/Cake/Controller/Controller.php line 678 → CakeEventManager->dispatch(CakeEvent)
CORE/Cake/Routing/Dispatcher.php line 189 → Controller->startupProcess()
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(BannersController, CakeRequest)
APP/webroot/index.php line 108 → Dispatcher->dispatch(CakeRequest, CakeResponse)

## Single User Email Send
Invalid email: ""
Stack Trace
CORE/Cake/Network/Email/CakeEmail.php line 592 → CakeEmail->_validateEmail(string)
CORE/Cake/Network/Email/CakeEmail.php line 642 → CakeEmail->_setEmail(string, string, string)
CORE/Cake/Network/Email/CakeEmail.php line 387 → CakeEmail->_setEmailSingle(string, string, string, string)
APP/Model/PendingEmail.php line 73 → CakeEmail->from(string, string)
APP/Controller/UsersController.php line 2654 → PendingEmail->send(array, string)
[internal function] → UsersController->admin_sendMessage()
CORE/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(UsersController, array)
CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(UsersController, CakeRequest)
APP/webroot/index.php line 108 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by futurumclix** [comment]
1. It looks like you try to submit form after using the "back" button in your browser. Please enter the page again (by clicking "Promotional Banners" in "Settings" menu) and try again (best, with different file, as this one can be already uploaded, you can check this in /app/Media/Banners).
2. Please set the site e-mail address in "General Settings".

**Comment by kishor786** [comment]
1. I have been checked with your rules as your told me but same issue and  did not upload any Banners into /app/Media/Banners.

2. My site email is right setting because when users open an account then users get email form site email.

**Comment by futurumclix** [comment]
2. Sorry, I was looking in wrong method. Are you trying to send e-mail from admin/users/sendMessage URL? If so, please make sure you entered all the data (it looks like you have empty "Sender Name" or "Reply To". I will add validation here, so empty fields will not be accepted in newer versions.

**Comment by kishor786** [comment]
2. Yes if i do not empty any data then email send perfectly.
1. Please how can i solve the banner promotional banner issue.

**Comment by futurumclix** [comment]
2. Basically after adding e-mail to all users to queue it will be send (in portions, so server won't be too much loaded) when "frequent cron" is called (so you need to setup the cronjobs if you haven't already).
3. Please be patient, I will answer as soon as I identify the problem - I need to repeat it in my environment, but unfortunately everything I already tried works as it should be.

**Comment by futurumclix** [comment]
3. What web browser do you use? It looks like something is tampering request. Please use another one, preferably one without installed any extensions (especially adblock ones).

**Comment by kishor786** [comment]
I tried Google Chrome and Mozila Firefox but same issue. I did not install adblock extension both of browsers.

**Comment by futurumclix** [comment]
As a workaround I can advice adding:
$this->Security->unlockedActions = array('admin_settings');
inside beforeFilter() method in BannersController.php, after line 51.

**Comment by kishor786** [comment]
I have added this code after $this->Auth->allow('image'); but same issue.
If i input url then show the error "Failed to download given file"

**Comment by futurumclix** [comment]
My last idea - please try adding to your core.ini.php configuration file following lines:
[compatibility]
disable_put = yes

**Comment by kishor786** [comment]
Yes it has been already added when i installed because for saving data from admin panel. :)

**Comment by futurumclix** [comment]
Do you have script installed on your own server or on external provider server?

**Comment by kishor786** [comment]
I have installed it in my server

**Comment by futurumclix** [comment]
Do you have installed haproxy? Please let me know what's software you have installed and which versions (OS, HTTP server, database, PHP, everything what's may be related). I will try to recreate your environment on some virtual machine and check what causing the bug to appear.

**Comment by kishor786** [comment]
If you want i will provide my server details your personal email and you can check you mind as you want to see.

**Comment by futurumclix** [comment]
First I would like to check on some VM, as it's more comfortable environment for tests. If that fails, we can try on your server.

**Comment by kishor786** [comment]
Apache Version | 2.4.29
PHP Version | 5.4.45
MySQL Version | 10.1.24-MariaDB-cll-lve
Operating System | linux
http://prntscr.com/i61n9b

**Comment by futurumclix** [comment]
Which distribution of Linux?

**Comment by kishor786** [comment]
I am using Apache

**Comment by futurumclix** [comment]
Is this server hosted by namecheap.com?

**Comment by kishor786** [comment]
Yes

**Comment by futurumclix** [comment]
Please ask Namecheap to disable haproxy for your server. It should solve the problem.

**Comment by kishor786** [comment]
It is not possible disabled because i am using share server

**Comment by kishor786** [comment]
Server Provider wants details about this issue please why it so not work ? Please write
